# JupyterBook settings. See https://jupyterbook.org/customize/config.html

title: SNN Sound localization
author: "the COMOB project: Colaboratively Modelling the Brain"

execute:
  execute_notebooks: "off"  # Do not try to re-run notebooks when building the website.

# Do not try and convert files to html that are not explicitly listed in the generated
# table of contents. We still need to explicitly exclude files in hidden folders from
# being build (weirdly). See https://jupyterbook.org/structure/configure.html#disable-building-files-that-arent-in-the-table-of-contents
only_build_toc_files: true
exclude_patterns: [.github/*]

# bibtex_bibfiles:
  # - references.bib

html:
  baseurl: https://comob-project.github.io/snn-sound-localization
  home_page_in_navbar:   false   # Clicking website logo/title already brings you to
                                 # home page. No need for extra TOC entry.
  extra_navbar: ""               # Text under TOC. Default: "Powered by JupyterBook".
  use_repository_button: true    # gh logo to go to repo
  use_issues_button:     false   # "Open issue" button in gh logo dropdown
  use_edit_page_button:  true    # "Suggest edit" button in gh logo dropdown.
  comments:
    hypothesis: true             # Adds the Hypothesis script to every page, which adds
                                 # a sidebar to add and see in-situ comments.

repository:
  url: https://github.com/comob-project/snn-sound-localization
  # branch: main
