name: comob_soundloc_build-jb-website
  # (`jb` is the standard abbreviation for JupyterBook).

channels:
  - conda-forge
  - nodefaults                # only use one channel (`conda-forge`).

dependencies:
  - python = 3.10             # To be able to use the newest syntax in build script.
                              # (But patch version is free).
  - jupyter-book = 0.12.3     # Newest release at time of writing.
                              # Pinned so that the website build keeps working as expected.
  - pyyaml = 6                # To modify jb's _config.yml and _toc.yml
